export const META = {
  title: 'CON:SEAT - See it before you Sit',
  siteName: 'CON:SEAT | 콘시트',
  shortName: 'CON:SEAT',
  description: '한눈에 확인하는 콘서트장 시야',
  keyword: [
    '콘시트',
    'conseat',
    'concert seat',
    '콘서트',
    '콘서트 시야',
    '시야',
    'KSPO DOME',
    '체조 경기장',
    '올림픽 체조 경기장',
  ],
  url: 'https://concertseat.site',
  locale: 'ko_KR',
  googleVerification: 'NFr0xeiIKfCgAJlRtdK28kPLTBhTKBuamShxjWLsNRs',
  ogImage: '/og/main-og.png',
  twitterSite: '@con_see_at',
  twitterCreator: '@con_see_at',
} as const;
