name: Auto Assign Issue Creator

on:
  issues:
    types: [opened]

jobs:
  assign-issue-creator:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue creator
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueCreator = context.payload.issue.user.login;
            github.rest.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: [issueCreator]
            });
